# Generated by Django 4.2.7 on 2025-09-01 23:37

import django.core.validators
from django.db import migrations, models
import document_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='modification_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='modified_file',
            field=models.FileField(blank=True, null=True, upload_to=document_api.models.modified_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('modifying', 'Modifying'), ('modified', 'Modified')], default='pending', max_length=20),
        ),
    ]
