# Generated by Django 4.2.7 on 2025-09-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0002_document_modification_guidelines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('modifying', 'Modifying'), ('modified', 'Modified'), ('no_changes', 'No Changes Needed')], default='pending', max_length=20),
        ),
    ]
